routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::get('/realhome', function () {
    return view('welcome');
})->name('home');

Route::resource('artiste','ArtisteController');
Route::resource('film','FilmController');
Route::resource('cinema','CinemaController');
Route::resource('salle','SalleController');
Route::resource('seance','SeanceController');


// Auth::routes();
Route::get('/logout', function(){
    Auth::logout();

    return redirect('/');
});

Route::auth();

Route::get('/home', 'HomeController@index')->name('home');



Route::get('/edit','ArtisteController@edit')->middleware('auth');

app/Models/Artiste.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Artiste extends Model
{
    use SoftDeletes;
    
    protected $fillable = [
        'nom','prenom','annee_naissance'
    ];

    public function films_realises(){
        return $this->hasMany('App\Models\Film');
    }

    public function films_joues(){
        return $this->belongsToMany('App\Models\Film')->withPivot('nom_role');
    }

}

app/Http/Controllers/ArtisteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ArtisteRequest;
use App\Models\Artiste;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\InterventionImage as Image;
use App\Policies\ArtistePolicy;


class ArtisteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //dd(Artiste::where('annee_naissance', '>' ,1980)->get());
        return view('artistes.index', [ 'artistes' => Artiste::all() ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(ArtisteRequest $request)
    {
        return view('artistes.create');


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArtisteRequest $request)
    {
        $artiste = Artiste::create($request->all());
        return redirect()->route('home')
                        ->with('ok', __ ('L‘artiste a bien ete enregistre'));

        $poster = $request->file('poster');
        $filename = 'poster_' . $artiste->id . '.' . $poster->getClientOriginalExtension();
        Image::make($poster)->fit( 180,240 )->save( public_path( '/uploads/posters/' . $filename));

        auth()->user->notify(new ArtisteCreated($artiste));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Artiste $artiste)
    {
        $this->authorize('update',$artiste);

        return view('artistes.edit',['artiste' => $artiste]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ArtisteRequest $request, Artiste $artiste)
    {
        // $this->authorize('artistes.edit',$artiste);

        $artiste->update( $request->all() );

        return redirect()->route('artiste.index')
                        ->with('ok', __('L‘artiste a bien ete modifie'));
        
        $poster = $request->file('poster');
        $filename = 'poster_' . $artiste->id . '.' . $poster->getClientOriginalExtension();
        Image::make($poster)->fit( 180,240 )->save( public_path( '/uploads/posters/' . $filename));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Artiste $artiste)
    {
        $artiste->delete();
        return response()->json();
    }

    public function __construct()
    {
        $this->middleware('ajax')->only('destroy');
        $this->middleware('auth')->only('edit');
    }
}

resources/views/artistes/create.blade.php
@extends('layouts.app')

@section('title', 'My Form, Laravel')

@section('content')

<form method="POST" action="{{ route('artiste.store') }}">
    {{ csrf_field() }}

    <p>
        <label for="nom">Nom</label>
        <input class="form-control" type="text" name="nom" id="nom" value="" require />
        @if ($errors->has('nom'))
        <div class="invalid-feedback">
            {{ $errors->first('nom') }}
        </div>
        @endif
    </br>
        <label for="prenom">Prenom</label>
        <input type="text" name="prenom" id="prenom" value="" require />
        @if ($errors->has('prenom'))
        <div class="invalid-feedback">
            {{ $errors->first('prenom') }}
        </div>
        @endif
    </br>
        <label for="annee_naisance">Annee Naissance</label>
        <input type="number" name="annee_naissance" id="annee_naissance" value="" />
        @if ($errors->has('annee_naissance'))
        <div class="invalid-feedback">
            {{ $errors->first('annee_naissance') }}
        </div>
        @endif
    </p>

    <button type="submit">Creer</button>
</form>
@endsection

resources/views/artistes/edit.blade.php
@extends('layouts.app')

@section('title', 'My Form, Laravel')

@section('content')

<form method="POST" action="{{ route('artiste.update',$artiste->id) }}" enctype="multipart/form-data">
    {{ csrf_field() }}
    {{ method_field('PUT')}} 

    <p>
        <label for="nom">Nom</label>
    <input class="form-control" type="text" name="nom" id="nom" value="{{ $artiste->nom }}" require />

        @if ($errors->has('nom'))
        <div class="invalid-feedback">
            {{ $errors->first('nom') }}
        </div>
        @endif

    </br>
        <label for="prenom">Prenom</label>
        <input type="text" name="prenom" id="prenom" value="{{ $artiste->prenom }}" require />

        @if ($errors->has('prenom'))
        <div class="invalid-feedback">
            {{ $errors->first('prenom') }}
        </div>
        @endif

    </br>
        <label for="annee_naisance">Annee Naissance</label>
        <input type="number" name="annee_naissance" id="annee_naissance" value="{{ $artiste->annee_naissance }}" />

        @if ($errors->has('annee_naissance'))
        <div class="invalid-feedback">
            {{ $errors->first('annee_naissance') }}
        </div>
        @endif
        
    </br>
        <label for="poster">Select image to upload:</label>
        <input type="file" name="poster" id="poster">
    </p>

    <button type="submit">Creer</button>
</form>
@endsection

resources/views/artistes/index.blade.php
@extends('layouts.app')

@section('title', 'My Form, Laravel')

@section('content')
<table>
    <thead>
        <tr>
            <th>{{ __('Nom') }}</th>
            <th>{{ __('Actions') }}</th>
        </tr>
    </thead>
    <tbody>
        @foreach($artistes as $artiste)
            <tr>
                <td>{{ $artiste->nom }}</td>
                <td class="table-action">
                    <a type="button" href="{{ route('artiste.edit', $artiste->id) }}" class="btn btn-sm"
                            data-toggle="tooltip" title="@lang('modifier l‘artiste') {{ $artiste->nom }}">
                        <i class="fas fa-edit fa-lg">Edit</i>
                    </a>

                    <a type="button" href="{{ route('artiste.destroy', $artiste->id) }}" class="btn btn-danger btn-sm artiste_destroy"
                        data-toggle="tooltip" title="@lang('suprimer l‘artiste') {{ $artiste->nom }}">
                    <i class="fas fa-edit fa-lg">Destroy</i>
                </a>
                </td>
            </tr>
    @endforeach
    </tbody>
    
</table>
@endsection