routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::get('/realhome', function () {
    return view('welcome');
})->name('home');

Route::resource('artiste','ArtisteController');
Route::resource('film','FilmController');
Route::resource('cinema','CinemaController');
Route::resource('salle','SalleController');
Route::resource('seance','SeanceController');


// Auth::routes();
Route::get('/logout', function(){
    Auth::logout();

    return redirect('/');
});

Route::auth();

Route::get('/home', 'HomeController@index')->name('home');



Route::get('/edit','ArtisteController@edit')->middleware('auth');

app/Models/Film.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Film extends Model
{
    //use softDeletes
    //TODO make a migration for the soft deletes

    protected $fillable = [
        'titre','annee'
    ];

    public function realisateur(){
        return $this->belongsTo('App\Models\Artiste');
    }

    public function acteurs(){
        return $this->belongsToMany('App\Models\Artiste');
    }
}

app/Http/Controllers/FilmController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\FilmRequest;
use App\Models\Film;
use Intervention\Image\Facades\InterventionImage as Image;



class FilmController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        // dd(Film::whereHas('realisateur')->get());
        // dd( $this->getEloquentSqlWithBindings(Film::whereHas('realisateur')));
        return view('films.index', [ 'films' => Film::all() ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('films.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FilmRequest $request)
    {
        $film = Film::create($request->all());
        Film::create($request->all());
        return redirect()->route('home')
                        ->with('ok', __ ('L‘film a bien ete enregistre'));

        $poster = $request->file('poster');
        $filename = 'poster_' . $film->id . '.' . $poster->getClientOriginalExtension();
        Image::make($poster)->fit( 180,240 )->save( public_path( '/uploads/posters/' . $filename));

        auth()->user->notify(new FilmCreated($film));
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Film $film)
    {
        return view('films.edit',['film' => $film]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(FilmRequest $request, Film $film)
    {
        $film->update( $request->all() );

        return redirect()->route('film.index')
                        ->with('ok', __('L‘film a bien ete modifie'));

        $poster = $request->file('poster');
        $filename = 'poster_' . $film->id . '.' . $poster->getClientOriginalExtension();
        Image::make($poster)->fit( 180,240 )->save( public_path( '/uploads/posters/' . $filename));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Film $film)
    {
        $film->delete();
        return response()->json();
    }

    public function __construct()
    {
        $this->middleware('ajax')->only('destroy');
    }

    public static function getEloquentSqlWithBindings($query)
    {
        return vsprintf(str_replace('?', '%s', $query->toSql()), collect($query->getBindings())->map(function ($binding) {
            return is_numeric($binding) ? $binding : "'{$binding}'";
        })->toArray());
    }
}

resources/views/films/create.blade.php
@extends('layouts.app')

@section('title', 'My Form, Laravel')

@section('content')

<form method="POST" action="{{ route('film.store') }}">
    {{ csrf_field() }}

    <p>
        <label for="titre">Titre</label>
        <input class="form-control" type="text" name="titre" id="titre" value="" require />
        @if ($errors->has('titre'))
        <div class="invalid-feedback">
            {{ $errors->first('titre') }}
        </div>
        @endif
    </br>
        <label for="annee">Annee</label>
        <input type="text" name="annee" id="annee" value="" require />
        @if ($errors->has('annee'))
        <div class="invalid-feedback">
            {{ $errors->first('annee') }}
        </div>
        @endif
    </br>
        <label for="realisateur">Realisateur</label>
        <input type="number" name="artiste_id" id="artiste_id" value="" />
        @if ($errors->has('artiste_id'))
        <div class="invalid-feedback">
            {{ $errors->first('artiste_id') }}
        </div>
        @endif
    </p>

    <button type="submit">Creer</button>
</form>
@endsection

resources/views/films/edit.blade.php
@extends('layouts.app')

@section('title', 'My Form, Laravel')

@section('content')

<form method="POST" action="{{ route('film.update',$film->id) }}" enctype="multipart/form-data">
    {{ csrf_field() }}
    {{ method_field('PUT')}} 

    <p>
        <label for="titre">Titre</label>
    <input class="form-control" type="text" name="titre" id="titre" value="{{ $film->titre }}" require />

        @if ($errors->has('titre'))
        <div class="invalid-feedback">
            {{ $errors->first('titre') }}
        </div>
        @endif

    </br>
        <label for="annee">Annee</label>
        <input type="text" name="annee" id="annee" value="{{ $film->annee }}" require />

        @if ($errors->has('annee'))
        <div class="invalid-feedback">
            {{ $errors->first('annee') }}
        </div>
        @endif

    </br>
        <label for="realisateur">Realisateur</label>
        <input type="number" name="artiste_id" id="artiste_id" value="{{ $film->artiste_id }}" />

        @if ($errors->has('artiste_id'))
        <div class="invalid-feedback">
            {{ $errors->first('artiste_id') }}
        </div>
        @endif
        
    </br>
        <label for="poster">Select image to upload:</label>
        <input type="file" name="poster" id="poster">
    </p>

    <button type="submit">Creer</button>
</form>
@endsection

resources/views/films/index.blade.php
@extends('layouts.app')

@section('title', 'My Form, Laravel')

@section('content')
<table>
    <thead>
        <tr>
            <th>{{ __('Titre') }}</th>
            <th>{{ __('Annee') }}</th>
            <th>{{ __('Realisateur') }}</th>
            <th>{{ __('Actions') }}</th>
        </tr>
    </thead>
    <tbody>
        @foreach($films as $film)
            <tr>
                <td>{{ $film->titre }}</td>
                <td>{{ $film->annee }}</td>
                <td>{{ $film->artiste_id }}</td>
                <td class="table-action">
                    <a type="button" href="{{ route('film.edit', $film->id) }}" class="btn btn-sm"
                            data-toggle="tooltip" title="@lang('modifier l‘artiste') {{ $film->nom }}">
                        <i class="fas fa-edit fa-lg">Edit</i>
                    </a>

                    <a type="button" href="{{ route('film.destroy', $film->id) }}" class="btn btn-danger btn-sm artiste_destroy"
                        data-toggle="tooltip" title="@lang('suprimer l‘artiste') {{ $film->nom }}">
                    <i class="fas fa-edit fa-lg">Destroy</i>
                </a>
                </td>
            </tr>
    @endforeach
    </tbody>
    
</table>
@endsection