routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::get('/realhome', function () {
    return view('welcome');
})->name('home');

Route::resource('artiste','ArtisteController');
Route::resource('film','FilmController');
Route::resource('cinema','CinemaController');
Route::resource('salle','SalleController');
Route::resource('seance','SeanceController');


// Auth::routes();
Route::get('/logout', function(){
    Auth::logout();

    return redirect('/');
});

Route::auth();

Route::get('/home', 'HomeController@index')->name('home');



Route::get('/edit','ArtisteController@edit')->middleware('auth');

app/Models/Cinema.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Cinema extends Model
{
    //use softDeletes;

    protected $fillable = [
        'nom_cinema','arrondissement','adresse'
    ];

    public function salles(){
        return $this->hasMany('App\Models\Room');
    }
}

app/Http/Controllers/CinemaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CinemaRequest;
use App\Models\Cinema;


class CinemaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('cinemas.index', [ 'cinemas' => Cinema::all() ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cinemas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CinemaRequest $request)
    {
        $cinema = Cinema::create($request->all());
        return redirect()->route('home')
                        ->with('ok', __ ('L‘artiste a bien ete enregistre'));


        auth()->user->notify(new CinemaCreated($cinema));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Cinema $cinema)
    {
        $this->authorize('update',$cinema);

        return view('cinemas.edit',['cinema' => $cinema]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CinemaRequest $request, Cinema $cinema)
    {
        $cinema->update( $request->all() );

        return redirect()->route('cinema.index')
                        ->with('ok', __('Le cinema a bien ete modifie'));
        
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cinema $cinema)
    {
        $cinema->delete();
        return response()->json();
    }

    public function __construct()
    {
        $this->middleware('ajax')->only('destroy');
        $this->middleware('auth')->only('edit');
    }
}

resources/views/cinemas/create.blade.php
@extends('layouts.app')

@section('title', 'My Form, Laravel')

@section('content')

<form method="POST" action="{{ route('cinema.store') }}">
    {{ csrf_field() }}

    <p>
        <label for="nom_cinema">Nom du cinema</label>
        <input class="form-control" type="text" name="nom_cinema" id="nom_cinema" value="" require />
        @if ($errors->has('nom_cinema'))
        <div class="invalid-feedback">
            {{ $errors->first('nom_cinema') }}
        </div>
        @endif
    </br>
        <label for="arrondissement">Arrondissement</label>
        <input type="text" name="arrondissement" id="arrondissement" value="" require />
        @if ($errors->has('arrondissement'))
        <div class="invalid-feedback">
            {{ $errors->first('arrondissement') }}
        </div>
        @endif
    </br>
        <label for="adresse">Adresse</label>
        <input type="number" name="adresse" id="adresse" value="" />
        @if ($errors->has('adresse'))
        <div class="invalid-feedback">
            {{ $errors->first('adresse') }}
        </div>
        @endif
    </p>

    <button type="submit">Creer</button>
</form>
@endsection

resources/views/cinemas/edit.blade.php
@extends('layouts.app')

@section('title', 'My Form, Laravel')

@section('content')

<form method="POST" action="{{ route('cinema.update',$cinema->id) }}" enctype="multipart/form-data">
    {{ csrf_field() }}
    {{ method_field('PUT')}} 

    <p>
        <label for="nom_cinema">Nom du cinema</label>
    <input class="form-control" type="text" name="nom_cinema" id="nom_cinema" value="{{ $cinema->nom_cinema }}" require />

        @if ($errors->has('nom_cinema'))
        <div class="invalid-feedback">
            {{ $errors->first('nom_cinema') }}
        </div>
        @endif

    </br>
        <label for="arrondissement">Arrondissement</label>
        <input type="text" name="arrondissement" id="arrondissement" value="{{ $cinema->arrondissement }}" require />

        @if ($errors->has('arrondissement'))
        <div class="invalid-feedback">
            {{ $errors->first('arrondissement') }}
        </div>
        @endif

    </br>
        <label for="adresse">Adresse</label>
        <input type="number" name="adresse" id="adresse" value="{{ $cinema->adresse }}" />

        @if ($errors->has('adresse'))
        <div class="invalid-feedback">
            {{ $errors->first('adresse') }}
        </div>
        @endif


    <button type="submit">Creer</button>
</form>
@endsection

resources/views/cinemas/index.blade.php
@extends('layouts.app')

@section('title', 'My Form, Laravel')

@section('content')
<table>
    <thead>
        <tr>
            <th>{{ __('Cinema') }}</th>
            <th>{{ __('Arrondissement') }}</th>
            <th>{{ __('Adresse') }}</th>
            <th>{{ __('Actions') }}</th>
        </tr>
    </thead>
    <tbody>
        @foreach($cinemas as $cinema)
            <tr>
                <td>{{ $cinema->nom_cinema }}</td>
                <td>{{ $cinema->arrondissement }}</td>
                <td>{{ $cinema->adresse }}</td>
                <td class="table-action">
                    <a type="button" href="{{ route('cinema.edit', $cinema->id) }}" class="btn btn-sm"
                            data-toggle="tooltip" title="@lang('modifier l‘artiste') {{ $cinema->nom }}">
                        <i class="fas fa-edit fa-lg">Edit</i>
                    </a>

                    <a type="button" href="{{ route('cinema.destroy', $cinema->id) }}" class="btn btn-danger btn-sm artiste_destroy"
                        data-toggle="tooltip" title="@lang('suprimer l‘artiste') {{ $cinema->nom }}">
                    <i class="fas fa-edit fa-lg">Destroy</i>
                </a>
                </td>
            </tr>
    @endforeach
    </tbody>
    
</table>
@endsection